export const mockRowData = [
  {
    id: 1,
    programm: "Прикладная математика и информатика",
    code: "03.04.05",
    recYear: 2020,
    educLvl: "Магистратура",
  },
  {
    id: 2,
    programm: "Физика",
    code: "03.02.01",
    recYear: 2019,
    educLvl: "Бакалавриат",
  },
  {
    id: 3,
    programm: "Химия",
    code: "04.02.01",
    recYear: 2022,
    educLvl: "Бакалавриат",
  },
  {
    id: 4,
    programm: "Биология",
    code: "06.02.01",
    recYear: 2021,
    educLvl: "Магистратура",
  },
  {
    id: 5,
    programm: "Прикладная математика и информатика",
    code: "03.04.05",
    recYear: 2018,
    educLvl: "Магистратура",
  },
  {
    id: 6,
    programm: "Физика",
    code: "03.02.01",
    recYear: 2020,
    educLvl: "Бакалавриат",
  },
  {
    id: 7,
    programm: "Химия",
    code: "04.02.01",
    recYear: 2019,
    educLvl: "Магистратура",
  },
  {
    id: 8,
    programm: "Биология",
    code: "06.02.01",
    recYear: 2022,
    educLvl: "Бакалавриат",
  },
  {
    id: 9,
    programm: "Прикладная математика и информатика",
    code: "03.04.05",
    recYear: 2021,
    educLvl: "Магистратура",
  },
  {
    id: 10,
    programm: "Физика",
    code: "03.02.01",
    recYear: 2018,
    educLvl: "Бакалавриат",
  },
  {
    id: 11,
    programm: "Химия",
    code: "04.02.01",
    recYear: 2020,
    educLvl: "Магистратура",
  },
  {
    id: 12,
    programm: "Биология",
    code: "06.02.01",
    recYear: 2019,
    educLvl: "Бакалавриат",
  },
  {
    id: 13,
    programm: "Прикладная математика и информатика",
    code: "03.04.05",
    recYear: 2022,
    educLvl: "Магистратура",
  },
  {
    id: 14,
    programm: "Физика",
    code: "03.02.01",
    recYear: 2018,
    educLvl: "Бакалавриат",
  },
  {
    id: 15,
    programm: "Прикладная информатика",
    code: "02.04.01",
    recYear: 2021,
    educLvl: "Магистратура",
  },
  {
    id: 16,
    programm: "Прикладная математика",
    code: "02.03.01",
    recYear: 2020,
    educLvl: "Бакалавриат",
  },
  {
    id: 17,
    programm: "Геофизика",
    code: "05.03.06",
    recYear: 2019,
    educLvl: "Магистратура",
  },
  {
    id: 18,
    programm: "Теология",
    code: "09.03.01",
    recYear: 2022,
    educLvl: "Бакалавриат",
  },
  {
    id: 19,
    programm: "Прикладная информатика",
    code: "02.04.01",
    recYear: 2022,
    educLvl: "Бакалавриат",
  },
  {
    id: 20,
    programm: "Прикладная математика",
    code: "02.03.01",
    recYear: 2021,
    educLvl: "Магистратура",
  },
  {
    id: 21,
    programm: "Геофизика",
    code: "05.03.06",
    recYear: 2020,
    educLvl: "Бакалавриат",
  },
  {
    id: 22,
    programm: "Теология",
    code: "09.03.01",
    recYear: 2019,
    educLvl: "Магистратура",
  },
  {
    id: 23,
    programm: "Прикладная информатика",
    code: "02.04.01",
    recYear: 2018,
    educLvl: "Бакалавриат",
  },
  {
    id: 24,
    programm: "Прикладная математика",
    code: "02.03.01",
    recYear: 2022,
    educLvl: "Магистратура",
  },
  {
    id: 25,
    programm: "Геофизика",
    code: "05.03.06",
    recYear: 2021,
    educLvl: "Бакалавриат",
  },
  {
    id: 26,
    programm: "Теология",
    code: "09.03.01",
    recYear: 2020,
    educLvl: "Магистратура",
  },
  {
    id: 27,
    programm: "Прикладная информатика",
    code: "02.04.01",
    recYear: 2019,
    educLvl: "Бакалавриат",
  },
  {
    id: 28,
    programm: "Прикладная математика",
    code: "02.03.01",
    recYear: 2018,
    educLvl: "Магистратура",
  },
  {
    id: 29,
    programm: "Геофизика",
    code: "05.03.06",
    recYear: 2022,
    educLvl: "Бакалавриат",
  },
  {
    id: 30,
    programm: "Теология",
    code: "09.03.02",
    recYear: 2021,
    educLvl: "Магистратура",
  },
  // ... and so on for the remaining objects
];
